version: '3.2'
services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /acme.json:/acme.json # needs to be created manually and you need to set chmod 600
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.frontend.rule=Host:visualizer.tsmean.com"
      - "traefik.domain=tsmean.com"

secrets:
  mailchimp.json:
    file: ./secrets/mailchimp.json

networks:
  web:
    external: true

#  demo-tsmean:
#    image: bersling/demo-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:demo.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  spinner-tsmean:
#    image: bersling/spinner-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:spinner.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  notify-tsmean:
#    image: bersling/notify-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:notify.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  mailchimp-tsmean:
#    image: bersling/mailchimp-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:mailchimp.tsmean.com"
#      - "traefik.domain=tsmean.com"

