version: '3.2'
services:
  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /acme.json:/acme.json # needs to be created manually and you need to set chmod 600
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.frontend.rule=Host:visualizer.tsmean.com"
      - "traefik.domain=tsmean.com"
  animals:
    image: bersling/animals
    labels:
      - "traefik.frontend.rule=Host:animals2.tsmean.com"
      - "traefik.domain=tsmean.com"
  mailchimp:
    image: bersling/mailchimp
    secrets:
      config:
        file: ./secrets/mailchimp.json
    labels:
      - "traefik.frontend.rule=Host:mailchimp2.tsmean.com"
      - "traefik.domain=tsmean.com"

#  demo-tsmean:
#    image: bersling/demo-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:demo.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  spinner-tsmean:
#    image: bersling/spinner-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:spinner.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  notify-tsmean:
#    image: bersling/notify-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:notify.tsmean.com"
#      - "traefik.domain=tsmean.com"
#  mailchimp-tsmean:
#    image: bersling/mailchimp-tsmean
#    labels:
#      - "traefik.frontend.rule=Host:mailchimp.tsmean.com"
#      - "traefik.domain=tsmean.com"

