version: '3.2'
services:
  traefik:
    image: traefik:1.6
    env_file:
      - ./secrets/route53.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /acme.json:/acme.json # needs to be created manually and you need to set chmod 600
    networks:
      - traefik
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.frontend.rule=Host:monitor.tsmean.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik"
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
  visualizer:
    image: dockersamples/visualizer
    networks:
      - traefik
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      labels:
        - "traefik.frontend.rule=Host:visualizer.tsmean.com"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik"
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

secrets:
  mailchimp.json:
    file: ./secrets/mailchimp.json

networks:
  traefik:
    external:
      name: traefik

