version: '3.2'
services:
  traefik:
    image: traefik
    env_file:
      - ./secrets/route53.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /acme.json:/acme.json # needs to be created manually and you need to set chmod 600
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
  visualizer:
    image: dockersamples/visualizer
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.frontend.rule=Host:visualizer.tsmean.com"
      - "traefik.domain=tsmean.com"

secrets:
  mailchimp.json:
    file: ./secrets/mailchimp.json

networks:
  web:
    external: true
